apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  quarkus_oidc_auth_server_url: {{ .Values.api.quarkus_oidc_auth_server_url }}
  template_dir: {{ .Values.api.template_dir }}
  consolidation_dir: {{ .Values.api.consolidation_dir }}