apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  quarkus_oidc_auth_client_id: {{ .Values.api.quarkus_oidc_auth_client_id | b64enc }}
  quarkus_oidc_auth_secret: {{ .Values.api.quarkus_oidc_auth_secret | b64enc }}