apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: backend-api
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    name: {{ .Release.Name }}